# Generated by Django 4.2.4 on 2023-09-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auction_starting_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='starting_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
