# Generated by Django 4.2.4 on 2023-09-19 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_bid_auction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='auction',
        ),
        migrations.AlterField(
            model_name='auction',
            name='date_of_auction',
            field=models.DateField(default=datetime.date(2023, 9, 19), null=True),
        ),
    ]
