# Generated by Django 4.2.4 on 2023-09-21 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_rename_category_category_category_lsit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_lsit',
            new_name='category_list',
        ),
    ]
